#
# NyvariaCore Configuration
#

use-metrics: true

group-labels:
  Admins:
    - ServerOwners
    - SeniorAdmins
    - AssociateAdmins
    - JuniorAdmins
  Moderators:
    - SeniorMods
    - JuniorMods
  Nyvarians:
    - Nyvarians
  Newbies:
    - Newbies
